// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyKXgZCh3A5onrd-pRUdjzJuJNeEcVFXI',
    appId: '1:46233423577:web:9df48fdb112e7d2c6e78c8',
    messagingSenderId: '46233423577',
    projectId: 'testing-cli-9a7da',
    authDomain: 'testing-cli-9a7da.firebaseapp.com',
    databaseURL: 'https://testing-cli-9a7da-default-rtdb.firebaseio.com',
    storageBucket: 'testing-cli-9a7da.appspot.com',
    measurementId: 'G-MSJ8309M7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAWdLPguS1kRmdUIANrNGWhiIQy4lC_nc',
    appId: '1:46233423577:android:1b58b1c2bae07d8f6e78c8',
    messagingSenderId: '46233423577',
    projectId: 'testing-cli-9a7da',
    databaseURL: 'https://testing-cli-9a7da-default-rtdb.firebaseio.com',
    storageBucket: 'testing-cli-9a7da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2nl4bpR4kcRcPKiFQ_81XbJuyO8lZMFY',
    appId: '1:46233423577:ios:4f5da493dfbcfff16e78c8',
    messagingSenderId: '46233423577',
    projectId: 'testing-cli-9a7da',
    databaseURL: 'https://testing-cli-9a7da-default-rtdb.firebaseio.com',
    storageBucket: 'testing-cli-9a7da.appspot.com',
    iosBundleId: 'com.example.fbases',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2nl4bpR4kcRcPKiFQ_81XbJuyO8lZMFY',
    appId: '1:46233423577:ios:4f5da493dfbcfff16e78c8',
    messagingSenderId: '46233423577',
    projectId: 'testing-cli-9a7da',
    databaseURL: 'https://testing-cli-9a7da-default-rtdb.firebaseio.com',
    storageBucket: 'testing-cli-9a7da.appspot.com',
    iosBundleId: 'com.example.fbases',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyKXgZCh3A5onrd-pRUdjzJuJNeEcVFXI',
    appId: '1:46233423577:web:e9394f5d5fc2482c6e78c8',
    messagingSenderId: '46233423577',
    projectId: 'testing-cli-9a7da',
    authDomain: 'testing-cli-9a7da.firebaseapp.com',
    databaseURL: 'https://testing-cli-9a7da-default-rtdb.firebaseio.com',
    storageBucket: 'testing-cli-9a7da.appspot.com',
    measurementId: 'G-NQM0J7E4LJ',
  );

}